app_sdepc: app.cpp 
	g++ -O3 app.cpp -o app -I/opt/Mohammad/bristol_projects/measurement/power_monitor_usermode/include/  -L/opt/Mohammad/bristol_projects/measurement/power_monitor_usermode/lib -lfpgaclmeasurement -lm -pthread
