// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// control_bus
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of positionsIn_offset
//        bit 31~0 - positionsIn_offset[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of positionsOut_offset
//        bit 31~0 - positionsOut_offset[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of velocitiesIn_offset
//        bit 31~0 - velocitiesIn_offset[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of velocitiesOut_offset
//        bit 31~0 - velocitiesOut_offset[31:0] (Read/Write)
// 0x2c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XNBODY_CONTROL_BUS_ADDR_AP_CTRL                   0x00
#define XNBODY_CONTROL_BUS_ADDR_GIE                       0x04
#define XNBODY_CONTROL_BUS_ADDR_IER                       0x08
#define XNBODY_CONTROL_BUS_ADDR_ISR                       0x0c
#define XNBODY_CONTROL_BUS_ADDR_POSITIONSIN_OFFSET_DATA   0x10
#define XNBODY_CONTROL_BUS_BITS_POSITIONSIN_OFFSET_DATA   32
#define XNBODY_CONTROL_BUS_ADDR_POSITIONSOUT_OFFSET_DATA  0x18
#define XNBODY_CONTROL_BUS_BITS_POSITIONSOUT_OFFSET_DATA  32
#define XNBODY_CONTROL_BUS_ADDR_VELOCITIESIN_OFFSET_DATA  0x20
#define XNBODY_CONTROL_BUS_BITS_VELOCITIESIN_OFFSET_DATA  32
#define XNBODY_CONTROL_BUS_ADDR_VELOCITIESOUT_OFFSET_DATA 0x28
#define XNBODY_CONTROL_BUS_BITS_VELOCITIESOUT_OFFSET_DATA 32

