// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// control_bus
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of in_X_offset
//        bit 31~0 - in_X_offset[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of in_Y_offset
//        bit 31~0 - in_Y_offset[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of a0
//        bit 31~0 - a0[31:0] (Read)
// 0x24 : Control signal of a0
//        bit 0  - a0_ap_vld (Read/COR)
//        others - reserved
// 0x28 : Data signal of a1
//        bit 31~0 - a1[31:0] (Read)
// 0x2c : Control signal of a1
//        bit 0  - a1_ap_vld (Read/COR)
//        others - reserved
// 0x30 : Data signal of a2
//        bit 31~0 - a2[31:0] (Read)
// 0x34 : Control signal of a2
//        bit 0  - a2_ap_vld (Read/COR)
//        others - reserved
// 0x38 : Data signal of n
//        bit 31~0 - n[31:0] (Read/Write)
// 0x3c : reserved
// 0x40 : Data signal of resultValid
//        bit 31~0 - resultValid[31:0] (Read)
// 0x44 : Control signal of resultValid
//        bit 0  - resultValid_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XPR_CONTROL_BUS_ADDR_AP_CTRL          0x00
#define XPR_CONTROL_BUS_ADDR_GIE              0x04
#define XPR_CONTROL_BUS_ADDR_IER              0x08
#define XPR_CONTROL_BUS_ADDR_ISR              0x0c
#define XPR_CONTROL_BUS_ADDR_IN_X_OFFSET_DATA 0x10
#define XPR_CONTROL_BUS_BITS_IN_X_OFFSET_DATA 32
#define XPR_CONTROL_BUS_ADDR_IN_Y_OFFSET_DATA 0x18
#define XPR_CONTROL_BUS_BITS_IN_Y_OFFSET_DATA 32
#define XPR_CONTROL_BUS_ADDR_A0_DATA          0x20
#define XPR_CONTROL_BUS_BITS_A0_DATA          32
#define XPR_CONTROL_BUS_ADDR_A0_CTRL          0x24
#define XPR_CONTROL_BUS_ADDR_A1_DATA          0x28
#define XPR_CONTROL_BUS_BITS_A1_DATA          32
#define XPR_CONTROL_BUS_ADDR_A1_CTRL          0x2c
#define XPR_CONTROL_BUS_ADDR_A2_DATA          0x30
#define XPR_CONTROL_BUS_BITS_A2_DATA          32
#define XPR_CONTROL_BUS_ADDR_A2_CTRL          0x34
#define XPR_CONTROL_BUS_ADDR_N_DATA           0x38
#define XPR_CONTROL_BUS_BITS_N_DATA           32
#define XPR_CONTROL_BUS_ADDR_RESULTVALID_DATA 0x40
#define XPR_CONTROL_BUS_BITS_RESULTVALID_DATA 32
#define XPR_CONTROL_BUS_ADDR_RESULTVALID_CTRL 0x44

