// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// bus_control
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of map_sw
//        bit 31~0 - map_sw[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of robotPose_dx_i
//        bit 31~0 - robotPose_dx_i[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of robotPose_dx_o
//        bit 31~0 - robotPose_dx_o[31:0] (Read)
// 0x24 : Control signal of robotPose_dx_o
//        bit 0  - robotPose_dx_o_ap_vld (Read/COR)
//        others - reserved
// 0x28 : Data signal of robotPose_dy_i
//        bit 31~0 - robotPose_dy_i[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of robotPose_dy_o
//        bit 31~0 - robotPose_dy_o[31:0] (Read)
// 0x34 : Control signal of robotPose_dy_o
//        bit 0  - robotPose_dy_o_ap_vld (Read/COR)
//        others - reserved
// 0x38 : Data signal of robotPose_theta_i
//        bit 31~0 - robotPose_theta_i[31:0] (Read/Write)
// 0x3c : reserved
// 0x40 : Data signal of robotPose_theta_o
//        bit 31~0 - robotPose_theta_o[31:0] (Read)
// 0x44 : Control signal of robotPose_theta_o
//        bit 0  - robotPose_theta_o_ap_vld (Read/COR)
//        others - reserved
// 0x48 : Data signal of bestTransformation_dx_i
//        bit 31~0 - bestTransformation_dx_i[31:0] (Read/Write)
// 0x4c : reserved
// 0x50 : Data signal of bestTransformation_dx_o
//        bit 31~0 - bestTransformation_dx_o[31:0] (Read)
// 0x54 : Control signal of bestTransformation_dx_o
//        bit 0  - bestTransformation_dx_o_ap_vld (Read/COR)
//        others - reserved
// 0x58 : Data signal of bestTransformation_dy_i
//        bit 31~0 - bestTransformation_dy_i[31:0] (Read/Write)
// 0x5c : reserved
// 0x60 : Data signal of bestTransformation_dy_o
//        bit 31~0 - bestTransformation_dy_o[31:0] (Read)
// 0x64 : Control signal of bestTransformation_dy_o
//        bit 0  - bestTransformation_dy_o_ap_vld (Read/COR)
//        others - reserved
// 0x68 : Data signal of bestTransformation_theta_i
//        bit 31~0 - bestTransformation_theta_i[31:0] (Read/Write)
// 0x6c : reserved
// 0x70 : Data signal of bestTransformation_theta_o
//        bit 31~0 - bestTransformation_theta_o[31:0] (Read)
// 0x74 : Control signal of bestTransformation_theta_o
//        bit 0  - bestTransformation_theta_o_ap_vld (Read/COR)
//        others - reserved
// 0x78 : Data signal of old_sw_dx
//        bit 31~0 - old_sw_dx[31:0] (Read/Write)
// 0x7c : reserved
// 0x80 : Data signal of old_sw_dy
//        bit 31~0 - old_sw_dy[31:0] (Read/Write)
// 0x84 : reserved
// 0x88 : Data signal of old_sw_theta
//        bit 31~0 - old_sw_theta[31:0] (Read/Write)
// 0x8c : reserved
// 0x90 : Data signal of p_x
//        bit 31~0 - p_x[31:0] (Read/Write)
// 0x94 : reserved
// 0x98 : Data signal of p_y
//        bit 31~0 - p_y[31:0] (Read/Write)
// 0x9c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XRUNITERATION_HW_BUS_CONTROL_ADDR_AP_CTRL                         0x00
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_GIE                             0x04
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_IER                             0x08
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_ISR                             0x0c
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_MAP_SW_DATA                     0x10
#define XRUNITERATION_HW_BUS_CONTROL_BITS_MAP_SW_DATA                     32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_ROBOTPOSE_DX_I_DATA             0x18
#define XRUNITERATION_HW_BUS_CONTROL_BITS_ROBOTPOSE_DX_I_DATA             32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_ROBOTPOSE_DX_O_DATA             0x20
#define XRUNITERATION_HW_BUS_CONTROL_BITS_ROBOTPOSE_DX_O_DATA             32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_ROBOTPOSE_DX_O_CTRL             0x24
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_ROBOTPOSE_DY_I_DATA             0x28
#define XRUNITERATION_HW_BUS_CONTROL_BITS_ROBOTPOSE_DY_I_DATA             32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_ROBOTPOSE_DY_O_DATA             0x30
#define XRUNITERATION_HW_BUS_CONTROL_BITS_ROBOTPOSE_DY_O_DATA             32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_ROBOTPOSE_DY_O_CTRL             0x34
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_ROBOTPOSE_THETA_I_DATA          0x38
#define XRUNITERATION_HW_BUS_CONTROL_BITS_ROBOTPOSE_THETA_I_DATA          32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_ROBOTPOSE_THETA_O_DATA          0x40
#define XRUNITERATION_HW_BUS_CONTROL_BITS_ROBOTPOSE_THETA_O_DATA          32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_ROBOTPOSE_THETA_O_CTRL          0x44
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_BESTTRANSFORMATION_DX_I_DATA    0x48
#define XRUNITERATION_HW_BUS_CONTROL_BITS_BESTTRANSFORMATION_DX_I_DATA    32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_BESTTRANSFORMATION_DX_O_DATA    0x50
#define XRUNITERATION_HW_BUS_CONTROL_BITS_BESTTRANSFORMATION_DX_O_DATA    32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_BESTTRANSFORMATION_DX_O_CTRL    0x54
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_BESTTRANSFORMATION_DY_I_DATA    0x58
#define XRUNITERATION_HW_BUS_CONTROL_BITS_BESTTRANSFORMATION_DY_I_DATA    32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_BESTTRANSFORMATION_DY_O_DATA    0x60
#define XRUNITERATION_HW_BUS_CONTROL_BITS_BESTTRANSFORMATION_DY_O_DATA    32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_BESTTRANSFORMATION_DY_O_CTRL    0x64
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_BESTTRANSFORMATION_THETA_I_DATA 0x68
#define XRUNITERATION_HW_BUS_CONTROL_BITS_BESTTRANSFORMATION_THETA_I_DATA 32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_BESTTRANSFORMATION_THETA_O_DATA 0x70
#define XRUNITERATION_HW_BUS_CONTROL_BITS_BESTTRANSFORMATION_THETA_O_DATA 32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_BESTTRANSFORMATION_THETA_O_CTRL 0x74
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_OLD_SW_DX_DATA                  0x78
#define XRUNITERATION_HW_BUS_CONTROL_BITS_OLD_SW_DX_DATA                  32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_OLD_SW_DY_DATA                  0x80
#define XRUNITERATION_HW_BUS_CONTROL_BITS_OLD_SW_DY_DATA                  32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_OLD_SW_THETA_DATA               0x88
#define XRUNITERATION_HW_BUS_CONTROL_BITS_OLD_SW_THETA_DATA               32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_P_X_DATA                        0x90
#define XRUNITERATION_HW_BUS_CONTROL_BITS_P_X_DATA                        32
#define XRUNITERATION_HW_BUS_CONTROL_ADDR_P_Y_DATA                        0x98
#define XRUNITERATION_HW_BUS_CONTROL_BITS_P_Y_DATA                        32

